In [229]:
import pandas as pd

Importazione file csv

In [247]:
routes = pd.read_csv('C:/Users/glori/OneDrive/Desktop/dataman/2.3.1-RoutesEU_NoDuplicate.csv', sep=",", encoding='latin-1')
airport = pd.read_csv('C:/Users/glori/OneDrive/Desktop/dataman/2.3-AirportEU.csv', sep=",", encoding='latin-1')
airline = pd.read_csv('C:/Users/glori/OneDrive/Desktop/dataman/2.1-AirlineEU.csv', sep=",", encoding='latin-1')

In [248]:
routes.head()

   Unnamed: 0          Airline Departure Arrivals Aircraft  Distance
0           0  Aegean Airlines       TIA      ATH      32N       529
1           1  Aegean Airlines       EVN      ATH      32N      1779
2           2  Aegean Airlines       VIE      ATH      320      1279
3           3  Aegean Airlines       BRU      ATH      320      2101
4           4  Aegean Airlines       SOF      ATH      320       531

In [232]:
airline.head()

   Unnamed: 0          Airline Airline_Code
0           0  Aegean Airlines       a3-aee
1           1       Aer Lingus       ei-ein
2           2         Aeroflot       su-afl
3           3      Air Albania       zb-abn
4           4       Air Astana       kc-kzr

In [145]:
airport.head()

,Unnamed: 0,Country,Country_Code,City,Airport_Name,Airport_Code
0,0,Albania,AL,Tirana,Tirana International Airport Nene Tereza,TIA
1,1,Armenia,AM,Gyumri,Shirak Airport,LWN
2,2,Armenia,AM,Yerevan,Zvartnots International Airport,EVN
3,3,Austria,AT,Graz,Flughafen Graz,GRZ
4,4,Austria,AT,Innsbruck,Innsbruck Airport,INN

Prima integrazione tra il dataset routes e airport (rispetto alla variabile Departure)

In [250]:
airport = airport.rename(columns={'Airport_Code': 'Departure'})

In [251]:
routes=routes.merge(airport, on='Departure', how='left')

Prima integrazione tra il dataset routes e airport (rispetto alla variabile Arrivals)

In [253]:
airport = airport.rename(columns={'Departure': 'Arrivals'})

In [254]:
routes=routes.merge(airport, on='Arrivals', how='left')

Integrazione manuale dei Missing Values

In [256]:
for i in range(len(routes)):
    if (routs.loc[i, 'Departure']=='ADA'):
        routs.loc[i, 'Country_x']='Turkey'
        routs.loc[i, 'Country_Code_x']='TR'
        routs.loc[i, 'City_x']='Adana'
        routs.loc[i, 'Airport_Name_x']='Adana Airport'
    if (routs.loc[i, 'Departure']=='ADB'):
         routs.loc[i, 'Country_x']='Turkey'
         routs.loc[i, 'Country_Code_x']='TR'
         routs.loc[i, 'City_x']='Izmir'
         routs.loc[i, 'Airport_Name_x']='Izmir Adnam Menderes Airport'
    if (routs.loc[i, 'Departure']=='ALA'):
         routs.loc[i, 'Country_x']='Kazakhstan'
         routs.loc[i, 'Country_Code_x']='KZ'
         routs.loc[i, 'City_x']='Almaty'
         routs.loc[i, 'Airport_Name_x']='Almaty International Airport'
    if (routs.loc[i, 'Departure']=='AYT'):
         routs.loc[i, 'Country_x']='Turkey'
         routs.loc[i, 'Country_Code_x']='TR'
         routs.loc[i, 'City_x']='Antalya'
         routs.loc[i, 'Airport_Name_x']='Antalya Airport'
    if (routs.loc[i, 'Departure']=='BJV'):
         routs.loc[i, 'Country_x']='Turkey'
         routs.loc[i, 'Country_Code_x']='TR'
         routs.loc[i, 'City_x']='Milas'
         routs.loc[i, 'Airport_Name_x']='Milas-Bodrum Airport'    
    if (routs.loc[i, 'Departure']=='DEB'):
         routs.loc[i, 'Country_x']='Hungary'
         routs.loc[i, 'Country_Code_x']='HU'
         routs.loc[i, 'City_x']='Debrecen'
         routs.loc[i, 'Airport_Name_x']='Debrecen International Airport' 
    if (routs.loc[i, 'Departure']=='DLM'):
         routs.loc[i, 'Country_x']='Turkey'
         routs.loc[i, 'Country_Code_x']='TR'
         routs.loc[i, 'City_x']='Dalaman'
         routs.loc[i, 'Airport_Name_x']='Dalaman Airport' 
    if (routs.loc[i, 'Departure']=='ESB'):
         routs.loc[i, 'Country_x']='Turkey'
         routs.loc[i, 'Country_Code_x']='TR'
         routs.loc[i, 'City_x']='Ankara'
         routs.loc[i, 'Airport_Name_x']='Ankara Esenboğa Airport'
    if (routs.loc[i, 'Departure']=='IST'):
         routs.loc[i, 'Country_x']='Turkey'
         routs.loc[i, 'Country_Code_x']='TR'
         routs.loc[i, 'City_x']='Istanbul'
         routs.loc[i, 'Airport_Name_x']='Istanbul Airport'
    if (routs.loc[i, 'Departure']=='PRN'):
         routs.loc[i, 'Country_x']='Kosovo'
         routs.loc[i, 'Country_Code_x']='XK'
         routs.loc[i, 'City_x']='Prishtina'
         routs.loc[i, 'Airport_Name_x']='Prishtina International Airport'
    if (routs.loc[i, 'Departure']=='SAW'):
         routs.loc[i, 'Country_x']='Turkey'
         routs.loc[i, 'Country_Code_x']='TR'
         routs.loc[i, 'City_x']='Istanbul'
         routs.loc[i, 'Airport_Name_x']='Istanbul Sabiha Gökçen International Airport'
    if (routs.loc[i, 'Departure']=='TZX'):
         routs.loc[i, 'Country_x']='Turkey'
         routs.loc[i, 'Country_Code_x']='TR'
         routs.loc[i, 'City_x']='Trabzon'
         routs.loc[i, 'Airport_Name_x']='Trabzon Airport'
    if (routs.loc[i, 'Departure']=='SKP'):
         routs.loc[i, 'Country_x']='Macedonia'
         routs.loc[i, 'Country_Code_x']='MK'
         routs.loc[i, 'City_x']='Skopje'
         routs.loc[i, 'Airport_Name_x']='Skopje International Airport'

In [257]:
for i in range(len(routes)):   
    if (routs.loc[i, 'Arrivals']=='BON'):
         routs.loc[i, 'Country_y']='Netherlands'
         routs.loc[i, 'Country_Code_y']='NL'
         routs.loc[i, 'City_y']='Kralendijk'
         routs.loc[i, 'Airport_Name_y']='Bonaire International Airport'
    if (routs.loc[i, 'Arrivals']=='BWF'):
         routs.loc[i, 'Country_y']='United kingdom'
         routs.loc[i, 'Country_Code_y']='UK'
         routs.loc[i, 'City_y']='Barrow-in-Furness'
         routs.loc[i, 'Airport_Name_y']='Barrow/Walney Island Airport'
    if (routs.loc[i, 'Arrivals']=='CAT'):
         routs.loc[i, 'Country_y']='Portugal'
         routs.loc[i, 'Country_Code_y']='PT'
         routs.loc[i, 'City_y']='Cascais'
         routs.loc[i, 'Airport_Name_y']='Cascais Airport'
    if (routs.loc[i, 'Arrivals']=='CDT'):
         routs.loc[i, 'Country_y']='Spain'
         routs.loc[i, 'Country_Code_y']='ES'
         routs.loc[i, 'City_y']='Benlloc'
         routs.loc[i, 'Airport_Name_y']='Castellón–Costa Azahar Airport'
    if (routs.loc[i, 'Arrivals']=='CFN'):
         routs.loc[i, 'Country_y']='Ireland'
         routs.loc[i, 'Country_Code_y']='IE'
         routs.loc[i, 'City_y']=' Bunbeg'
         routs.loc[i, 'Airport_Name_y']='Donegal Airport'
    if (routs.loc[i, 'Arrivals']=='DEB'):
         routs.loc[i, 'Country_y']='Hungary'
         routs.loc[i, 'Country_Code_y']='HU'
         routs.loc[i, 'City_y']='Debrecen'
         routs.loc[i, 'Airport_Name_y']='Debrecen International Airport'
    if (routs.loc[i, 'Arrivals']=='GNJ'):
         routs.loc[i, 'Country_y']='Azerbaijan'
         routs.loc[i, 'Country_Code_y']='AZ'
         routs.loc[i, 'City_y']='Ganja'
         routs.loc[i, 'Airport_Name_y']='Ganja International Airport'
    if (routs.loc[i, 'Arrivals']=='HOQ'):
         routs.loc[i, 'Country_y']='Germany'
         routs.loc[i, 'Country_Code_y']='DE'
         routs.loc[i, 'City_y']='Hof'
         routs.loc[i, 'Airport_Name_y']='Hof–Plauen Airport'
    if (routs.loc[i, 'Arrivals']=='IGS'):
         routs.loc[i, 'Country_y']='Germany'
         routs.loc[i, 'Country_Code_y']='DE'
         routs.loc[i, 'City_y']='Ingolstadt'
         routs.loc[i, 'Airport_Name_y']='Ingolstadt Manching Airport'
    if (routs.loc[i, 'Arrivals']=='ILD'):
         routs.loc[i, 'Country_y']='Spain'
         routs.loc[i, 'Country_Code_y']='ES'
         routs.loc[i, 'City_y']='Alguaire'
         routs.loc[i, 'Airport_Name_y']='Lleida–Alguaire Airport'
    if (routs.loc[i, 'Arrivals']=='LEU'):
         routs.loc[i, 'Country_y']='Andorra'
         routs.loc[i, 'Country_Code_y']='AD'
         routs.loc[i, 'City_y']='Alguaire'
         routs.loc[i, 'Airport_Name_y']='Andorra–La Seu Urgell Airport'
    if (routs.loc[i, 'Arrivals']=='MLH'):
         routs.loc[i, 'Country_y']='Switzerland'
         routs.loc[i, 'Country_Code_y']='CH'
         routs.loc[i, 'City_y']='Basel'
         routs.loc[i, 'Airport_Name_y']='EuroAirport Basel Mulhouse Freiburg'
    if (routs.loc[i, 'Arrivals']=='NAJ'):
         routs.loc[i, 'Country_y']='Azerbaijan'
         routs.loc[i, 'Country_Code_y']='AZ'
         routs.loc[i, 'City_y']='Nakhchivan'
         routs.loc[i, 'Airport_Name_y']='Nakhchivan International Airport'
    if (routs.loc[i, 'Arrivals']=='PRN'):
         routs.loc[i, 'Country_y']='Kosovo'
         routs.loc[i, 'Country_Code_y']='KS'
         routs.loc[i, 'City_y']='Prishtina'
         routs.loc[i, 'Airport_Name_y']='Prishtina International Airport'
    if (routs.loc[i, 'Arrivals']=='QGY'):
         routs.loc[i, 'Country_y']='Hungary'
         routs.loc[i, 'Country_Code_y']='HU'
         routs.loc[i, 'City_y']='Per'
         routs.loc[i, 'Airport_Name_y']='Gyor Per Airport'
    if (routs.loc[i, 'Arrivals']=='QKT'):
         routs.loc[i, 'Country_y']='Belgium'
         routs.loc[i, 'Country_Code_y']='BE'
         routs.loc[i, 'City_y']='Wevelgem'
         routs.loc[i, 'Airport_Name_y']='Wevelgem Airport'
    if (routs.loc[i, 'Arrivals']=='SXM'):
         routs.loc[i, 'Country_y']='Nederland'
         routs.loc[i, 'Country_Code_y']='NL'
         routs.loc[i, 'City_y']='Sint Maarten'
         routs.loc[i, 'Airport_Name_y']='Princess Juliana International Airport'
    if (routs.loc[i, 'Arrivals']=='XFW'):
         routs.loc[i, 'Country_y']='Germany'
         routs.loc[i, 'Country_Code_y']='DE'
         routs.loc[i, 'City_y']='Finkenwerder'
         routs.loc[i, 'Airport_Name_y']='Airbus Hamburg-Finkenwerder'
    if (routs.loc[i, 'Arrivals']=='BXO'):
         routs.loc[i, 'Country_y']='Switzerland'
         routs.loc[i, 'Country_Code_y']='CH'
         routs.loc[i, 'City_y']='Buochs'
         routs.loc[i, 'Airport_Name_y']='Airport Buochs'

Terza integrazione tra il dataset routes e airline

In [258]:
routes=routes.merge(airline, on='Airline', how='left')

C:\Users\glori\AppData\Local\Temp\ipykernel_22196\1720655677.py:1: FutureWarning: Passing 'suffixes' which cause duplicate columns {'Unnamed: 0_x'} in the result is deprecated and will raise a MergeError in a future version.
  routes=routes.merge(airline, on='Airline', how='left')

Eliminazione delle colonne superflue

In [259]:
routes.drop('Unnamed: 0_x', inplace=True, axis=1)
routes.drop('Unnamed: 0_y', inplace=True, axis=1)

Riordinare colonne del dataset integrato

In [261]:
routes = routes[['Airline','Airline_Code','Departure','Country_x','Country_Code_x','City_x', 'Airport_Name_x', 'Arrivals','Country_y','Country_Code_y','City_y', 'Airport_Name_y','Aircraft', 'Distance']]

In [262]:
routes.head()

,Airline,Airline_Code,Departure,Country_x,Country_Code_x,City_x,Airport_Name_x,Arrivals,Country_y,Country_Code_y,City_y,Airport_Name_y,Aircraft,Distance
0,Aegean Airlines,a3-aee,TIA,Albania,AL,Tirana,Tirana International Airport Nene Tereza,ATH,Greece,GR,Athens,Athens International Airport,32N,529
1,Aegean Airlines,a3-aee,EVN,Armenia,AM,Yerevan,Zvartnots International Airport,ATH,Greece,GR,Athens,Athens International Airport,32N,1779
2,Aegean Airlines,a3-aee,VIE,Austria,AT,Vienna,Vienna International Airport,ATH,Greece,GR,Athens,Athens International Airport,320,1279
3,Aegean Airlines,a3-aee,BRU,Belgium,BE,Brussels,Brussels Airport,ATH,Greece,GR,Athens,Athens International Airport,320,2101
4,Aegean Airlines,a3-aee,SOF,Bulgaria,BG,Sofia,Sofia Airport,ATH,Greece,GR,Athens,Athens International Airport,320,531

Esportazione a csv

In [228]:
routes.to_csv('C:/Users/glori/OneDrive/Desktop/dataman/RoutesIntegrato.csv')